server:
  port: 8088
  servlet:
    context-path: /uploadfiles

spring:
  cloud:
    config:
      enabled: false
  application:
    name: uploadfiles-service
  servlet:
    multipart.max-file-size:  500KB
    multipart.max-request-size: 500KB
    
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##ding
    password: peardoor807x

jpa:
  hibernate:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    ddl-auto: none
    
eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
          
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  api-docs:
   path: /v3/api-docs
  swagger-ui:
   path: /v3/swagger-ui.html  
  open-api:
    name: openApi Test
    email: roy@example.com
    license.name: my license 3.0

uploadfiles:
  topath: C:/tmp/tmp2
  ownerPermission: READ:WRITE:EXECUTE
  groupPermission: READ:WRITE:EXECUTE
  othersPermission: READ:WRITE:EXECUTE
  
filepermissions:
  owner:
    - OWNER_READ
    - OWNER_WRITE
    - OWNER_EXECUTE
  group:
    - GROUP_READ
    - GROUP_WRITE
    - GROUP_EXECUTE
  others:
    - OTHERS_READ
    - OTHERS_WRITE
    - OTHERS_EXECUTE    
   
auth:
  svcKey: upload-1234-5678   
  
app:
  jwt-secret: my-secret

app-jwt-expiration-milliseconds: 711100000

environment: local   


   